name = "openlist-workers"
main = "main.go"
compatibility_date = "2024-01-01"

[build]
command = "go build -o dist/worker main.go"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "openlist-db"
database_id = "your-database-id-here"

# 环境变量
[vars]
ENVIRONMENT = "production"

# 路由配置
[env.production.routes]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"